### ISSUE TITLE
Test and document REST API design

### ISSUE THREAD

**Issue by bajiat** [apinf/emq-rest-api#2]
# Definition of done
* [x] Test current REST API to make sure
  * [x] users can be created
  * [x] it is possible to create ACL rules for the users
* [x] API endpoints have documentation either in readme or as a Swagger document

**Comment by frenchbread** [comment]
Tested & verified workflow for adding users and acls. Authentication works as expected, comparing credentials to those that are stored in PostgreSQL DB. ACLs works as expected as well but requires some fixes which @phanimahesh is going to look into.

PR open for review: https://github.com/Digipalvelutehdas/emq-rest-api/pull/4 contains updated README with documented endpoints and some fixes related to EMQ-ACL & EMQ-USER schemas.

**Comment by frenchbread** [comment]
Closing this one as https://github.com/Digipalvelutehdas/emq-rest-api/pull/4 is merged
